rplab/rplab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from .initcmds import *

urlpatterns = [
    path('admin/', admin.site.urls), #AdminPage
    path('', home, name='home'), #HomePage
    path('home/', home, name='home'), #HomePage
    path('servizi/', servizi, name="servizi"), #Servizi
    path('about/', about, name="about"), #About
    path('contatti/', contatti, name="contatti"), #Contatti

    path('shop/', include('shop.urls')), #Shop App
    path('users/', include('users.urls')),  # Users App
    path('sell/', include('sell.urls')),  # Sell App

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#erase_db()
init_database()

rplab/sell/urls.py
from django.urls import path
from . import views

app_name = 'sell'

urlpatterns = [
    path('', views.home, name="homesell"), #Home
    path('valutazione/', views.valutazione, name="valutazione"), # Form valutazione 
    path('valutazione/success/<str:valutazione>', views.success, name="success"), # Valutazione eseguita
]

rplab/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='homeshop'), # HomeShop
    path('prodotti/', views.AllProductsListView.as_view(), name="prodotti"), # Lista prodotti
    path('brands/', views.AllBrandsListView.as_view(), name="brands"), # Lista brands
    path('prodotto/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'), # Prodotto nel dettaglio
    path('brand/<str:nome>/', views.ExploreProdcutsListView.as_view(), name="explore_brand"), # Lista prodotti in base al brand
    path('prodotto/<int:pk>/acquista/', views.acquista, name='acquista'), # Acquista
    path('checkout/<int:memoria>/<str:condizione>/<int:prodotto_pk>/', views.checkout, name='checkout'), # Checkout
    path('confirmed/<int:utente_pk>/<int:dettaglio_pk>', views.acquistoeffettuato, name='confermato'), # Conferma ordine
    path('search/', views.search, name='search'), # Cerca prodotti
    
]

rplab/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.register, name='register'), # Registazione utente
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'), # Login utente
    path('logout/', views.custom_logout, name='logout'), # Logout
    path('dashboard/', views.dashboard, name='dashboard'), # Dashboard
    path('comande/', views.all_comande_staff, name='allcomande'), # Tutte le comande (staff_only)
    path('valutazioni/', views.all_valutazioni_staff, name='allvalutazioni'), # Tutte le valutazioni (staff_only)
    path('', views.UserListView.as_view(), name='userlist'),  #Tutti gli utenti (staff_only)
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='userdetail'), # Dettagli utente
    path('users/<int:pk>/edit/', views.UserUpdateView.as_view(), name='userupdate'), # Modifica utente

    # CRUD HomePage
    path('gestione', views.crud_operations, name="gestione"),

    # Create
    path('createbrand', views.BrandCreateView.as_view(), name="brand_create"),
    path('createprodotto', views.ProdottoCreateView.as_view(), name="prodotto_create"),
    path('createdettaglio', views.DettaglioCreateView.as_view(), name="dettaglio_create"),
    path('createcomanda', views.ComandaCreateView.as_view(), name="comanda_create"),
    path('createvalutazione', views.ValutazioneCreateView.as_view(), name="valutazione_create"),

    # Select model to update
    path('select-brand-to-update', views.select_brand_to_update, name="brand_update"),
    path('select-prodotto-to-update', views.select_prodotto_to_update, name="prodotto_update"),
    path('select-dettaglio-to-update', views.select_dettaglio_to_update, name="dettaglio_update"),
    path('select-comanda-to-update', views.select_comanda_to_update, name="comanda_update"),
    path('select-valutazione-to-update', views.select_valutazione_to_update, name="valutazione_update"),

    # Update
    path('updatebrand/<int:pk>', views.BrandUpdateView.as_view(), name="selected_brand_update"), 
    path('updateprodotto/<int:pk>', views.ProdottoUpdateView.as_view(), name="selected_prodotto_update"),
    path('updatedettaglio/<int:pk>', views.DettaglioUpdateView.as_view(), name="selected_dettaglio_update"),
    path('updatecomanda/<int:pk>', views.ComandaUpdateView.as_view(), name="selected_comanda_update"),
    path('updatevalutazione/<int:pk>', views.ValutazioneUpdateView.as_view(), name="selected_valutazione_update"),

    # Select model to delete
    path('delete-brand-to-update', views.select_brand_to_delete, name="brand_delete"),
    path('delete-prodotto-to-update', views.select_prodotto_to_delete, name="prodotto_delete"),
    path('delete-dettaglio-to-update', views.select_dettaglio_to_delete, name="dettaglio_delete"),
    path('delete-comanda-to-update', views.select_comanda_to_delete, name="comanda_delete"),
    path('delete-valutazione-to-update', views.select_valutazione_to_delete, name="valutazione_delete"),


    # Delete
    path('deletebrand/<int:pk>', views.BrandDeleteView.as_view(), name="selected_brand_delete"), 
    path('deleteprodotto/<int:pk>', views.ProdottoDeleteView.as_view(), name="selected_prodotto_delete"),
    path('deletedettaglio/<int:pk>', views.DettaglioDeleteView.as_view(), name="selected_dettaglio_delete"),
    path('deletecomanda/<int:pk>', views.ComandaDeleteView.as_view(), name="selected_comanda_delete"),
    path('deletevalutazione/<int:pk>', views.ValutazioneDeleteView.as_view(), name="selected_valutazione_delete"),
]

rplab/shop/models.py
from django.db import models
from django.contrib.auth.models import User
import os


# Rinominare immagine brand e salvarla in percorso specifico

def rename_brand_image(instance):
    base_filename = instance.nome.replace(' ', '').lower()
    new_filename = f"{base_filename}.png"
    return os.path.join('shop/static/brands', new_filename)


# Rinominare immagine prodotto e salvarla in percorso specifico

def rename_product_image(instance):
    base_filename = instance.nome.replace(' ', '').lower()
    new_filename = f"{base_filename}.png"
    return os.path.join('shop/static/prodotti', new_filename)


# Brand

class Brand(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    immagine = models.ImageField(upload_to=rename_brand_image)

    def __str__(self):
        return self.nome


# Prodotto

class Prodotto(models.Model):
    nome = models.CharField(max_length=200)
    descrizione = models.TextField()
    modello = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='modello')
    immagine = models.ImageField(upload_to=rename_product_image)
    data_pub = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = "Prodotti"
        

# Possibili condizioni di prodotto

class Condizione(models.TextChoices):
    new = 'new', 'Nuovo'
    used = 'used', 'Usato'
    refurbished = 'refurbished', 'Ricondizionato'


# Possibili memorie di prodotto

class Memorie(models.IntegerChoices):
    GB_64 = 64, '64 GB'
    GB_128 = 128, '128 GB'
    GB_256 = 256, '256 GB'
    GB_512 = 512, '512 GB'
    TB_1 = 1024, '1 TB'

# Prodotto in dettaglio

class Dettagli(models.Model):
    prodotto = models.ForeignKey(Prodotto, on_delete=models.CASCADE, related_name='prodotto')
    condizione = models.CharField(max_length=15, choices=Condizione.choices)
    memoria = models.PositiveIntegerField(choices=Memorie.choices)
    prezzo = models.DecimalField(max_digits=10, decimal_places=2)
    quantita = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ('prodotto', 'condizione', 'memoria')
        verbose_name_plural = "Dettagli Prodotto"

    def __str__(self):
        return f"{self.prodotto.nome} ({self.condizione}) - {self.quantita} disponibili"
        

#Ordini effettuati

class Comanda(models.Model):
    utente = models.ForeignKey(User, on_delete=models.CASCADE, related_name="utente")
    dettagli = models.ForeignKey(Dettagli, on_delete=models.CASCADE, related_name="prodotto_dettaglio")  # Dettagli dell'acquisto (condizione, prezzo)
    data_acquisto = models.DateTimeField(auto_now_add=True)
    completata = models.BooleanField(blank=False, null=False, default=False)

    def __str__(self):
        return f"{self.id}: Acquisto di '{self.dettagli.prodotto.nome}' da '{self.utente.username}'"

    class Meta:
        verbose_name_plural = "Comande"

rplab/shop/forms.py
from django import forms
from .models import *


#Form per scegliere la condizione del prodotto da aquistare

class CondizioneProdottoForm(forms.Form):
    CONDITION_CHOICES = [
        ('new', 'Nuovo'),
        ('used', 'Usato'),
        ('refurbished', 'Ricondizionato'),
    ]
    MEMORY_CHOICES = [
        (64, '64 GB'),
        (128, '128 GB'),
        (256, '256 GB'),
        (512, '512 GB'),
        (1024, '1 TB'),
    ]
    condizione = forms.ChoiceField(choices=CONDITION_CHOICES, label="Seleziona condizione")
    memoria = forms.ChoiceField(choices=MEMORY_CHOICES, label="Seleziona memoria")

rplab/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from .forms import *
from .models import *


#Vista HomeShop

def home(request):
    brands = Brand.objects.all()
    prodotti = Prodotto.objects.all().order_by('-data_pub')[:6] #Visualizza solo gli ultimi 6 prodotti più recenti

    ctx = {"brands":brands,
           "prodotti":prodotti,
           "evidenza":"in evidenza"}

    return render(request, 'shop/home_shop.html', context=ctx)


#ListView prodotti

class AllProductsListView(ListView):
    model = Prodotto
    template_name = "shop/all_prodotti.html"
    context_object_name = "prodotti"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tot"] = self.model.objects.all().count()
        return context
    

#ListView brands

class AllBrandsListView(LoginRequiredMixin, ListView):
    model = Brand
    template_name = "shop/all_brand.html"
    context_object_name = "brands"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tot"] = self.model.objects.all().count()
        return context


#ListView Esplora Brand

class ExploreProdcutsListView(ListView):
    model = Prodotto
    template_name = "shop/esplora_brand.html"
    context_object_name = "prodotti"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["nome_brand"] = self.kwargs["nome"]
        return context

    def get_queryset(self):
        arg = self.kwargs["nome"]
        qs = self.model.objects.filter(modello=get_object_or_404(Brand, nome__icontains=arg))
        return qs    


#DetailView Prodotto
    
class ProductDetailView(DetailView):
    model = Prodotto
    template_name = "shop/detail_product.html"
    context_object_name = "prodotto"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["prezzoda"] = Dettagli.objects.get(prodotto=self.object, condizione='used', memoria=64).prezzo
        except:
            context["prezzoda"] = " non disponibile."
        return context
    
    
#Vista pagina acquisto

@login_required
def acquista(request, pk):
    if request.method == "POST":
        form = CondizioneProdottoForm(request.POST)
        if form.is_valid():
            condizione = form.cleaned_data['condizione']
            memoria = form.cleaned_data['memoria']
            prodotto = get_object_or_404(Prodotto, pk=pk)
            return redirect('shop:checkout', memoria=memoria, condizione=condizione, prodotto_pk=prodotto.pk)
    else:
        form = CondizioneProdottoForm()
        return render(request, 'shop/acquista.html', {"form":form})


#Vista pagina checkout

@login_required
def checkout(request, memoria, condizione, prodotto_pk):
    prodotto = get_object_or_404(Prodotto, pk=prodotto_pk)
    dettaglio = get_object_or_404(Dettagli, prodotto=prodotto, condizione=condizione, memoria=memoria)

    if request.method == "POST" and request.user.is_authenticated:
        user = request.user
        return redirect('shop:confermato', utente_pk=user.pk, dettaglio_pk=dettaglio.pk)
    else:
        return render(request, 'shop/checkout.html', {"prodotto":prodotto, "dettaglio":dettaglio})
    

# Vista per la ricerca di prodotti

def search(request):
    search_ctx = request.GET.get('search')
    if search_ctx:
        list_products = Prodotto.objects.filter(nome__icontains=search_ctx)
    else:
        return redirect('shop:homeshop')
    return render(request, 'shop/all_prodotti.html', {'search_ctx': search_ctx, 'prodotti': list_products})


# Vista pagina di acquisto effettuato

@login_required
def acquistoeffettuato(request, utente_pk, dettaglio_pk):
    utente = get_object_or_404(User, pk=utente_pk)
    dettaglio = get_object_or_404(Dettagli, pk=dettaglio_pk)

    if utente and dettaglio:
        new_comanda = Comanda()
        new_comanda.utente = utente
        new_comanda.dettagli = dettaglio
        new_comanda.data_acquisto = timezone.now()
        new_comanda.save()
        dettaglio.quantita -= 1
        dettaglio.save()

    return render(request, 'shop/acquisto_effettuato.html', {'utente':utente, 'dettagli':dettaglio})

rplab/shop/templates/shop/acquista.html
{% extends 'shop/base_shop.html' %}

{% block content %}

    {% if user.is_authenticated %}

        <div class="container">

            <!-- Form per l'acquisto -->
            <div class="card shadow">
                <div class="card-header">
                    Seleziona la Condizione
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="condizione">Scegli la Condizione del Prodotto:</label>
                            {{ form.condizione }}
                            <br>
                            <br>
                            <label for="memoria">Scegli la Memoria del Prodotto:</label>
                            {{ form.memoria }}
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-block ">Conferma</button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Indietro -->
            <div class="back-link">
                <a href="{% url 'shop:prodotti' %}" class="btn btn-link">Torna indietro</a>
            </div>
            
        </div>

    {% endif %}

{% endblock %}

rplab/shop/templates/shop/acquisto_effettuato.html
{% extends 'shop/base_shop.html' %}

{% block content %}

    {% if user.is_authenticated %}

        <!-- Pagina di acquisto confermato -->
        <div class="container text-center mt-5">
            <div class="alert alert-success" role="alert">
                <h1 class="display-4">Grazie per il tuo acquisto!</h1>
                <p class="lead">Il tuo ordine è stato confermato con successo.</p>
                <hr>
                <p>Puoi vedere tutti i tuoi ordini nella sezione <a href="{% url 'users:dashboard' %}">dashboard</a></p>
            </div>
            <a href="{% url 'shop:homeshop' %}" class="btn btn-primary btn-lg mt-3">Torna al Negozio</a>
        </div>

    {% endif %}
    
{% endblock %}

rplab/shop/templates/shop/all_brand.html
{% extends "shop/base_shop.html"%}

{% block head %}
    {% load static %}
{% endblock %}

{% block content %}

    <!-- Hero Section -->
    <header class="hero">
        <div class="container">
            <h1 class="display-4 fw-bold">Tutti i <span style="color = #CA421C;">Brand</span> ({{tot}})</h1>
            <p class="lead">Acquista telefoni nuovi, usati e ricondizionati al miglior prezzo!</p>
        </div>
    </header>

{% include 'shop/list_brand.html' %} <!-- Lista brand -->

{% endblock %}

rplab/shop/templates/shop/all_prodotti.html
{% extends "shop/base_shop.html"%}

{% block head %}
    {% load static %}
{% endblock %}

{% block content %}

    <!-- Hero Section -->
    <header class="hero">
        <div class="container">
            {% if search_ctx %}
                <h1 class="display-4 fw-bold">Ricerca per: <span style="color = #CA421C;">{{search_ctx}}</span></h1>
            {% else%}
                <h1 class="display-4 fw-bold">Tutti i <span style="color = #CA421C;">Prodotti</span> ({{tot}})</h1>
            {% endif %}
            <p class="lead">Acquista telefoni nuovi, usati e ricondizionati al miglior prezzo!</p>
        </div>
    </header>

{% include 'shop/list_product.html' %} <!-- Lista prodotti -->

{% endblock %}

rplab/shop/templates/shop/base_shop.html
{% extends 'base.html' %}

{% block head %}
    {% load static %}
{% endblock %}

{% block content %}

    {% block nav %}

        <!-- Mini Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'shop:homeshop' %}">Shop</a>
                <div class="collapse navbar-collapse">

                    <!-- Link a sinistra -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:prodotti' %}">Prodotti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:brands' %}">Brands</a>
                        </li>
                    </ul>

                    <!-- Barra di ricerca al centro -->
                    <form class="d-flex mx-auto" method="GET" action="{% url 'shop:search' %}">
                        <div class="input-group">
                            <input id="search-input" type="search" name="search" class="form-control rounded-pill" placeholder="Cerca prodotti..." style="border-top-right-radius: 0; border-bottom-right-radius: 0;">
                            <button id="search-button" class="btn btn-outline-success rounded-pill" type="submit" style="margin-left: 5px; border-top-left-radius: 0; border-bottom-left-radius: 0;">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </form>

                    <!-- Link a destra -->
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}

                            {% if user.is_staff %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'users:gestione' %}">Gestione</a>
                                </li>
                            {% endif %}

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:dashboard' %}">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <form method="post" action="{% url 'users:logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-link nav-link" style="color: black; border: none; background: none;">Logout</button>
                                </form>
                            </li>

                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:register' %}">Registrati</a>
                            </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
        
        <!-- Script per rendere non cliccabile il pulsante se non scritto niente nella barra di ricerca -->
        <script src="{% static 'js/disable_search_button.js' %}"></script>

    {% endblock %}
    
{% endblock %}

rplab/shop/templates/shop/checkout.html
{% extends 'shop/base_shop.html' %}

{% block head %}
    {% load static %}
{% endblock %}

{% block content %}

    {% if user.is_authenticated %}

        <!-- Card Riepilogo Ordine -->
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="card">
                        
                        <!-- Titolo -->
                        <div class="card-header text-center">
                            <h3>Riepilogo Ordine</h3>
                        </div>
                        
                        <!-- Riepilogo -->
                        <div class="card-body">

                            <div class="col-md-12">
                                <img src="{{prodotto.immagine.url}}" class="img-fluid" alt="{{ prodotto.nome }}">
                            </div>

                            <h2 class="mb-3">Dettagli:</h4>

                            <div class="mb-3">
                                <strong>Prodotto:</strong> {{ prodotto.nome }}
                            </div>

                            <div class="mb-3">
                                <strong>Condizione:</strong> {{ dettaglio.condizione }}
                            </div>

                            <div class="mb-3">
                                <strong>Memoria:</strong> {{ dettaglio.memoria }} GB
                            </div>

                            <div class="mb-3">
                                <strong>Descrizione:</strong> {{ prodotto.descrizione }}
                            </div>

                            <div class="mb-3">
                                <strong>Prezzo:</strong> €{{ dettaglio.prezzo }}
                            </div>

                            <div class="mb-3">
                                {% if dettaglio.quantita > 0 %} <!-- Se prodotto disponibile -->

                                    <strong>Quantità disponibile:</strong> {{ dettaglio.quantita }} pz
                                    <div class="text-center">

                                        <form method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-success">Acquista</button>
                                            <a href="{% url 'shop:acquista' prodotto.pk%}" class="btn btn-secondary">Indietro</a>
                                        </form>
                                    </div>

                                {% else %} <!-- Se prodotto NON disponibile -->

                                    <strong>Quantità disponibile:</strong> <p style="color: red; display: inline;"> {{ dettaglio.quantita }}</div>
                                    <div class="text-center">
                                        <a class="btn btn-danger">Non disponibile</a>
                                        <a href="{% url 'shop:acquista' prodotto.pk%}" class="btn btn-secondary">Indietro</a>
                                    </div>
                                    
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}

{% endblock %}

rplab/shop/templates/shop/detail_product.html
{% extends 'shop/base_shop.html' %}

{% block head%}
    {% load static %}
{% endblock %}

{% block content %}

    <!-- Hero Section -->
    <header class="hero">
        <div class="container">
            <h1 class="display-4 fw-bold">Dettagli del Prodotto</h1>
        </div>
    </header>

    <!-- Dettaglio Prodotto -->
    <div class="container my-5">
        <div class="row">

            <div class="col-md-6">

                {% if prodotto.immagine%}
                    <img src="{{prodotto.immagine.url}}" class="img-fluid" alt="{{ prodotto.nome }}">
                {% endif %}
            </div>

            <div class="col-md-6">
                <h2>{{ prodotto.nome }}</h2>
                <p><strong>Brand:</strong> {{ prodotto.modello }}</p>
                <p><strong>Descrizione:</strong> {{ prodotto.descrizione }}</p>
                <p><strong>Prezzo:</strong> da € {{ prezzoda }}</p>
                
                {% if user.is_authenticated %} <!-- Se utente è autenticato -->
                    <a href="{% url 'shop:acquista' prodotto.pk%}" class="btn btn-success">Scegli...</a>
                {% else %} <!-- Se utente NON è autenticato -->
                    <a href="{% url 'users:register' %}" class="btn btn-primary">Registrati</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Accedi</a>
                {% endif%}
                <a href="{% url 'shop:prodotti' %}" class="btn btn-secondary">Torna alla lista dei prodotti</a>
            </div>

        </div>
    </div>
    
{% endblock %}

rplab/shop/templates/shop/esplora_brand.html
{% extends 'shop/base_shop.html' %}

{% block head%}
    {% load static %}
{% endblock %}

{% block content %}

    <!-- Hero Section -->
    <header class="hero">
        <div class="container">
            <h1 class="display-4 fw-bold">Prodotti <span style="color = #CA421C;">{{nome_brand}}</span></h1>
            <p class="lead">Acquista telefoni nuovi, usati e ricondizionati al miglior prezzo!</p>
        </div>
    </header>

{% include 'shop/list_product.html' %} <!-- Lista prodotti -->

{% endblock %}

rplab/shop/templates/shop/home_shop.html
{% extends "shop/base_shop.html"%}

{% block head %}
    {% load static %}
{% endblock %}

{% block content %}

    <!-- Hero Section -->
    <header class="hero">
        <div class="container">
            <h1 class="display-4 fw-bold">Benvenuto nello <span style="color = #CA421C;">Shop</span></h1>
            <p class="lead">Acquista telefoni nuovi, usati e ricondizionati al miglior prezzo!</p>
        </div>
    </header>

{% include 'shop/list_brand.html' %}  <!-- Lista brand -->

{% include 'shop/list_product.html' %} <!-- Lista prodotti -->

    <div class="text-center" >
        <a id="red" class="btn btn-outline-primary mt-3" href="{% url 'shop:prodotti' %}" style="margin: 80px;"><strong>Altro...</strong></a>
    </div>

{% endblock %}

rplab/shop/templates/shop/list_brand.html
{% block head %}
    {% load static %}
{% endblock %}

    <!-- Vetrina -->
    <section class="bg-light py-5">
        <div class="container">

            {% if evidenza %}
                <h2 class="text-center mb-4">Brand {{evidenza}}:</h2>
            {% else %}
                <h2 class="text-center mb-4">Brand:</h2>
            {% endif%}

            <div class="row">

                {% if brands %} <!-- Se esistono brand -->

                    {% for brand in brands %} <!-- Per ogni brand esistente -->
                    <div class="col-md-3">
                        <div class="card mb-4 shadow-sm">

                            {% if brand.immagine %}
                                <img src="{{brand.immagine.url}}" class="card-img-top" alt="{{ brand.nome }}">
                            {% endif %}

                            <div class="card-body text-center">
                                <h5 class="card-title">{{ brand.nome }}</h5>
                                <a href="/shop/brand/{{brand.nome|lower}}" class="btn btn-primary">Esplora</a>
                            </div>

                        </div>
                    </div>
                    {% endfor %}

                {% else %} <!-- Se NON esistono brand -->
                    <div class="col-md">
                        <div class="card product-card mb shadow-sm">
                            <div class="card-body">
                                <h2 style="text-align: center;"class="card-title">Nessuno brand disponibile.</h2>
                            </div>
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </section>

rplab/shop/templates/shop/list_product.html
{% block head %}
    {% load static %}
{% endblock %}

    <!-- Vetrina -->
    <section id="products" class="py-5">
        <div class="container">

            {% if evidenza %}
                <h2 class="text-center mb-4">Prodotti {{evidenza}}:</h2>
            {% else %}
                <h2 class="text-center mb-4">Prodotti:</h2>
            {% endif %}

            <div class="row">

                {% if prodotti %} <!-- Se esistono prodotti -->

                    {% for prodotto in prodotti %} <!-- Per ogni prodotto esistente -->
                        <div class="col-md-4">
                            <div class="card product-card mb-4 shadow-sm">
                                
                                {% if prodotto.immagine %}
                                    <img height="auto" src="{{prodotto.immagine.url}}" class="card-img-top" alt="{{ prodotto.nome }}">
                                {% endif %}

                                <div class="card-body">
                                    <h5 class="card-title">{{prodotto.modello.nome}} {{ prodotto.nome }}</h5>
                                    <p class="desc card-text text-muted">{{ prodotto.descrizione }}</p>
                                    <div class="text-center">
                                        <a href="/shop/prodotto/{{prodotto.pk}}" class="btn btn-outline-primary">Scopri di più</a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    {% endfor %}

                {% else %} <!-- Se NON esistono prodotti -->
                    <div class="col-md">
                        <div class="card product-card mb shadow-sm">
                            <div class="card-body">
                                <h2 style="text-align: center;"class="card-title">Nessuno articolo disponibile.</h2>
                            </div>
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </section>

    <!-- Script per ridurre caratteri descrizione -->
    <script src="{% static 'js/reduce_text.js' %}"></script>