rplab/rplab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from .initcmds import *

urlpatterns = [
    path('admin/', admin.site.urls), #AdminPage
    path('', home, name='home'), #HomePage
    path('home/', home, name='home'), #HomePage
    path('servizi/', servizi, name="servizi"), #Servizi
    path('about/', about, name="about"), #About
    path('contatti/', contatti, name="contatti"), #Contatti

    path('shop/', include('shop.urls')), #Shop App
    path('users/', include('users.urls')),  # Users App
    path('sell/', include('sell.urls')),  # Sell App

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#erase_db()
init_database()

rplab/sell/urls.py
from django.urls import path
from . import views

app_name = 'sell'

urlpatterns = [
    path('', views.home, name="homesell"), #Home
    path('valutazione/', views.valutazione, name="valutazione"), # Form valutazione 
    path('valutazione/success/<str:valutazione>', views.success, name="success"), # Valutazione eseguita
]

rplab/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='homeshop'), # HomeShop
    path('prodotti/', views.AllProductsListView.as_view(), name="prodotti"), # Lista prodotti
    path('brands/', views.AllBrandsListView.as_view(), name="brands"), # Lista brands
    path('prodotto/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'), # Prodotto nel dettaglio
    path('brand/<str:nome>/', views.ExploreProdcutsListView.as_view(), name="explore_brand"), # Lista prodotti in base al brand
    path('prodotto/<int:pk>/acquista/', views.acquista, name='acquista'), # Acquista
    path('checkout/<int:memoria>/<str:condizione>/<int:prodotto_pk>/', views.checkout, name='checkout'), # Checkout
    path('confirmed/<int:utente_pk>/<int:dettaglio_pk>', views.acquistoeffettuato, name='confermato'), # Conferma ordine
    path('search/', views.search, name='search'), # Cerca prodotti
    
]

rplab/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.register, name='register'), # Registazione utente
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'), # Login utente
    path('logout/', views.custom_logout, name='logout'), # Logout
    path('dashboard/', views.dashboard, name='dashboard'), # Dashboard
    path('comande/', views.all_comande_staff, name='allcomande'), # Tutte le comande (staff_only)
    path('valutazioni/', views.all_valutazioni_staff, name='allvalutazioni'), # Tutte le valutazioni (staff_only)
    path('', views.UserListView.as_view(), name='userlist'),  #Tutti gli utenti (staff_only)
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='userdetail'), # Dettagli utente
    path('users/<int:pk>/edit/', views.UserUpdateView.as_view(), name='userupdate'), # Modifica utente

    # CRUD HomePage
    path('gestione', views.crud_operations, name="gestione"),

    # Create
    path('createbrand', views.BrandCreateView.as_view(), name="brand_create"),
    path('createprodotto', views.ProdottoCreateView.as_view(), name="prodotto_create"),
    path('createdettaglio', views.DettaglioCreateView.as_view(), name="dettaglio_create"),
    path('createcomanda', views.ComandaCreateView.as_view(), name="comanda_create"),
    path('createvalutazione', views.ValutazioneCreateView.as_view(), name="valutazione_create"),

    # Select model to update
    path('select-brand-to-update', views.select_brand_to_update, name="brand_update"),
    path('select-prodotto-to-update', views.select_prodotto_to_update, name="prodotto_update"),
    path('select-dettaglio-to-update', views.select_dettaglio_to_update, name="dettaglio_update"),
    path('select-comanda-to-update', views.select_comanda_to_update, name="comanda_update"),
    path('select-valutazione-to-update', views.select_valutazione_to_update, name="valutazione_update"),

    # Update
    path('updatebrand/<int:pk>', views.BrandUpdateView.as_view(), name="selected_brand_update"), 
    path('updateprodotto/<int:pk>', views.ProdottoUpdateView.as_view(), name="selected_prodotto_update"),
    path('updatedettaglio/<int:pk>', views.DettaglioUpdateView.as_view(), name="selected_dettaglio_update"),
    path('updatecomanda/<int:pk>', views.ComandaUpdateView.as_view(), name="selected_comanda_update"),
    path('updatevalutazione/<int:pk>', views.ValutazioneUpdateView.as_view(), name="selected_valutazione_update"),

    # Select model to delete
    path('delete-brand-to-update', views.select_brand_to_delete, name="brand_delete"),
    path('delete-prodotto-to-update', views.select_prodotto_to_delete, name="prodotto_delete"),
    path('delete-dettaglio-to-update', views.select_dettaglio_to_delete, name="dettaglio_delete"),
    path('delete-comanda-to-update', views.select_comanda_to_delete, name="comanda_delete"),
    path('delete-valutazione-to-update', views.select_valutazione_to_delete, name="valutazione_delete"),


    # Delete
    path('deletebrand/<int:pk>', views.BrandDeleteView.as_view(), name="selected_brand_delete"), 
    path('deleteprodotto/<int:pk>', views.ProdottoDeleteView.as_view(), name="selected_prodotto_delete"),
    path('deletedettaglio/<int:pk>', views.DettaglioDeleteView.as_view(), name="selected_dettaglio_delete"),
    path('deletecomanda/<int:pk>', views.ComandaDeleteView.as_view(), name="selected_comanda_delete"),
    path('deletevalutazione/<int:pk>', views.ValutazioneDeleteView.as_view(), name="selected_valutazione_delete"),
]

rplab/users/models.py
from django.db import models

rplab/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import EmailValidator
from shop.models import *
from sell.models import *


# Form per la registrazione utente

class UserRegistrationForm(UserCreationForm):
    numero_di_telefono = forms.CharField(min_length=10, max_length=10, required=True)
    email = forms.EmailField(max_length=254, required=True, validators=[EmailValidator()])

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'numero_di_telefono', 'username', 'password1', 'password2',]


# Form per la selezione del Brand 

class BrandSelectionForm(forms.Form):
    selection = forms.ModelChoiceField(queryset=Brand.objects.all(), empty_label="Seleziona un Brand", widget=forms.Select)


# Form per la selezione del Prodotto

class ProdottoSelectionForm(forms.Form):
    selection = forms.ModelChoiceField(queryset=Prodotto.objects.all(), empty_label="Seleziona un Prodotto", widget=forms.Select)


# Form per la selezione del Dettaglio 

class DettaglioSelectionForm(forms.Form):
    selection = forms.ModelChoiceField(queryset=Dettagli.objects.all(), empty_label="Seleziona un Dettaglio", widget=forms.Select)


# Form per la selezione della Comanda 

class ComandaSelectionForm(forms.Form):
    selection = forms.ModelChoiceField(queryset=Comanda.objects.all(), empty_label="Seleziona una Comanda", widget=forms.Select)


# Form per la selezione della Valutazione 

class ValutazioneSelectionForm(forms.Form):
    selection = forms.ModelChoiceField(queryset=Valutazione.objects.all(), empty_label="Seleziona una Comanda", widget=forms.Select)

rplab/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import logout
from shop.models import Comanda
from sell.models import Valutazione
from .forms import *
from .crud_views.create import *
from .crud_views.update import *
from .crud_views.delete import *


#Vista registrazione utente

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Registrazione completata! Ora puoi effettuare il login.')
            return redirect('users:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'users/register.html', {'form': form})


#Vista dashboard utente

@login_required
def dashboard(request):
    comande = Comanda.objects.filter(utente=request.user).order_by('-data_acquisto')
    valutazioni = Valutazione.objects.filter(utente=request.user).order_by('-id')

    comande_attive = Comanda.objects.all().filter(completata=False).order_by('-data_acquisto')
    valutazioni_attive = Valutazione.objects.all().filter(completata=False).order_by('id')

    return render(request, 'users/dashboard.html', {"comande":comande,
                                                    "valutazioni":valutazioni,
                                                    "comande_attive":comande_attive,
                                                    "valutazioni_attive":valutazioni_attive,
                                                    })


#Vista logout utente

@login_required
def custom_logout(request):
    logout(request)
    return redirect('users:login')


# Vista tutte le comande
@staff_member_required
def all_comande_staff(request):
    comande = Comanda.objects.all()
    return render(request, 'users/staff_all_comande.html', {"comande_attive":comande,
                                                            "title":"Tutte le comande:"})
                                                                

# Vista tutte le valutazioni
@staff_member_required
def all_valutazioni_staff(request):
    valutazioni = Valutazione.objects.all()
    return render(request, 'users/staff_all_valutazioni.html', {"valutazioni_attive":valutazioni,
                                                            "title":"Tutte le valutazioni:"})


# Classe Lista Utenti

class UserListView(ListView):
    model = User
    template_name = 'users/user_list.html'
    context_object_name = 'utente'


# Classe Dettaglio Utente
                                                    
class UserDetailView(DetailView):
    model = User
    template_name = 'users/user_detail.html'
    context_object_name = 'utente'


# Vista pagina homepage per le operazione CRUD

@staff_member_required
def crud_operations(request):
    operation = request.GET.get('operazione')
    model = request.GET.get('modello')

    if operation and model:
        url_name = f"{model}_{operation}" 
        print("URL_NAME: " + url_name) # Es: "brand_create"
        return redirect('users:' + url_name)
    else:
        return render(request, "users/CRUD/home_crud.html")


#Classe per la modifica di un utente

class UserUpdateView(UpdateView):
    model = User
    template_name = 'users/modifica_utente.html'
    fields = ['username', 'first_name', 'last_name', 'email']
    context_object_name = 'utente'

    def get_success_url(self):
        # Dopo la modifica, ritorna alla lista utenti
        return reverse_lazy('users:userlist')

rplab/users/templates/users/dashboard.html
{% extends 'users/dashboard_base.html' %}

{% block dashboard %}

    {% include 'users/user_orders_list.html' %} <!-- Lista ordini utente -->

    {% include 'users/staff_orders_list.html' %} <!-- Lista valutazioni utenti -->

    {% if user.is_admin or user.is_staff%}
        <div class="text-center">
            <a href="{% url 'users:allcomande' %}" class="btn btn-outline-primary">Vedi tutte...</a>
        </div>
    {% endif %}

    <!-- Separator -->
    <div class="separator"></div>

    {% include 'users/user_valutazioni_list.html' %} <!-- Lista di tutti gli ordini -->

    {% include 'users/staff_valutazioni_list.html' %} <!-- Lista di tutte le valutazioni -->

    {% if user.is_admin or user.is_staff%}
        <div class="text-center">
            <a href="{% url 'users:allvalutazioni' %}" class="btn btn-outline-primary">Vedi tutte...</a>
        </div>
    {% endif %}
    
{% endblock %}

rplab/users/templates/users/dashboard_base.html
{% extends 'base.html' %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/colors.css' %}">
{% endblock %}

{% block content%}

    {% if user %}

        <!-- Welcome Section -->
        <div class="text-center">
            {% if user.first_name and user.last_name%}
                <h2>Benvenuto/a, <strong>{{user.first_name}} {{user.last_name}}</strong>!</h2>
            {% else %}
                <h2>Benvenuto/a, <strong>{{user.username}}</strong>!</h2>
            {% endif %}

            <p>Questa è la tua dashboard personale.</p>

            {% if user.is_superuser%} <!-- Se utente superuser -->
                <h5><i>Sei un utente <strong>superuser</strong></i></h5>
            {% elif user.is_staff %} <!-- Se utente staff -->
                <h5><i>Sei un utente <strong>staff</strong></i></h5>
            {% endif %}
        </div>

        {% block dashboard%}

        {% endblock %}

        <div class="mt-5 text-center">

            <!-- Pulsanti per utenti normali -->
            {% if not user.is_admin and not user.is_staff%}
                <a href="{% url 'shop:homeshop' %}" class="btn btn-primary">Acquista</a>
                <a href="{% url 'sell:homesell' %}" class="btn btn-primary">Vendi</a>

            {% endif %}
            
            <!-- Pulsanti per qualsiasi utente -->
            <a href="{% url 'users:dashboard' %}" class="btn btn-warning">Dashboard</a>
            <a href="{% url 'users:logout' %}" class="btn btn-danger">Logout</a>

            <!-- Pulsanti per staff e superuser -->
            {% if user.is_staff or user.is_superuser %}
                <a href="{% url 'users:gestione' %}" class="btn btn-success">Gestione</a>
                <a href="{% url 'users:userlist' %}" class="btn btn-primary">Lista Utenti</a>
            {% endif %}
            
        </div>
    {% endif %}


    <!-- Script Popper per funzionamento "Leggi commento" -->
    <script src="{% static 'js/popper.js' %}"></script>

{% endblock %}

rplab/users/templates/users/login.html
{% extends 'base.html' %}

{% block content%}

    <h2 class="text-center mb-4">Accedi</h2>

    <!-- Login Form -->
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary w-100">Accedi</button>
    </form>

    <div class="mt-3 text-center">
        <p>Non hai un account? <a href="{% url 'users:register' %}">Registrati</a></p>
    </div>

{% endblock %}

rplab/users/templates/users/logout.html
{% extends 'base.html' %}

{% block content%}

    <div class="text-center">
        <h2>Logout effettuato con successo</h2>
        <p>Sei stato disconnesso dal tuo account.</p>

        <form method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Accedi di nuovo</button>
        </form>
    </div>

{% endblock %}

rplab/users/templates/users/modifica_utente.html
{% extends 'users/dashboard_base.html' %}

{% block dashboard %}

    <!-- Form modifica utente -->
    <div class="container mt-5">
        <h2 class="mb-4">Modifica Utente</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Salva</button>
                <a href="{% url 'users:userlist' %}" class="btn btn-secondary">Annulla</a>
            </div>
        </form>
    </div>

{% endblock %}

rplab/users/templates/users/register.html
{% extends 'base.html' %}

{% block content%}

    <h2 class="text-center mb-4">Registrati</h2>

    <!-- Form registrazione utente -->
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary w-100">Registrati</button>
    </form>

    <div class="mt-3 text-center">
        <p>Hai già un account? <a href="{% url 'users:login' %}">Accedi</a></p>
    </div>

{% endblock %}

rplab/users/templates/users/staff_all_comande.html
{% extends 'users/dashboard_base.html' %}

{% block dashboard %}

    {% include 'users/staff_orders_list.html' %} <!-- Tutti gli ordini -->

    <div class="text-center">
        <a href="{% url 'users:dashboard' %}" class="btn btn-secondary">Indietro</a>
    </div>
    
{% endblock %}

rplab/users/templates/users/staff_all_valutazioni.html
{% extends 'users/dashboard_base.html' %}

{% block dashboard %}

    {% include 'users/staff_valutazioni_list.html' %} <!-- Tutte le valutazioni -->
    
    <div class="text-center">
        <a href="{% url 'users:dashboard' %}" class="btn btn-secondary">Indietro</a>
    </div>

{% endblock %}

rplab/users/templates/users/staff_orders_list.html
<div class="mt-5 text-center">
    {% if user.is_staff or user.is_superuser %} <!-- Se utente staff o superuser -->

        {% if title %}
            <h3>{{title}}</h3>
        {% else %}
            <h3>Comande attive:</h3>
        {% endif %}

        <!-- Tabella comande -->
        {% if comande_attive %}
            <table class="table table-bcomandaed">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Acquirente</th>
                        <th>Brand</th>
                        <th>Modello</th>
                        <th>Condizione</th>
                        <th>Memoria</th>
                        <th>Prezzo</th>
                        <th>Data</th>
                        <th>Stato</th>
                        <th>Modifica</th>
                        <th>Elimina</th>
                    </tr>
                </thead>

                <tbody>
                    {% for comanda in comande_attive %}
                    <tr>
                        <td>{{ comanda.pk }}</td>
                        <td><a href="{% url 'users:userdetail' comanda.utente.id %}" class="btn-primary">{{ comanda.utente.username }}</a></td>
                        <td>{{ comanda.dettagli.prodotto.modello.nome }}</td>
                        <td>{{ comanda.dettagli.prodotto.nome }}</td>
                        <td>{{ comanda.dettagli.condizione }}</td>
                        <td>{{ comanda.dettagli.memoria }} GB</td>
                        <td>{{ comanda.dettagli.prezzo }} €</td>
                        <td>{{ comanda.data_acquisto }}</td>
                        {% if comanda.completata %}
                            <td>✔</td>
                        {% else %}
                            <td>⏳</td>
                        {% endif %}
                        
                        <!-- Modifica -->
                        <td>
                            <a href="{% url 'users:selected_comanda_update' comanda.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                    <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708z"></path>
                                </svg>
                            </a>
                        </td>
                        
                        <!-- Elimina -->
                        <td>
                            <a href="{% url 'users:selected_comanda_delete' comanda.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                </svg>
                            </a>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        {% else %}
            <p>Non ci sono ordini attivi.</p>
        {% endif %}
        
    {% endif %}
    
</div>

rplab/users/templates/users/staff_valutazioni_list.html
<div class="mt-5 text-center">
    {% if user.is_staff or user.is_superuser %} <!-- Se utente staff o superuser -->

    {% if title %}
        <h3>{{title}}</h3>
    {% else %}
        <h3>Valutazioni attive:</h3>
    {% endif %}

        <!-- Tabella valutazioni -->
        {% if valutazioni_attive %}
            <table class="table table-bcomandaed">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Acquirente</th>
                        <th>Brand</th>
                        <th>Prodotto</th>
                        <th>Memoria</th>
                        <th>Condizione</th>
                        <th>Schermo Rotto</th>
                        <th>Back Rotto</th>
                        <th>Stato Batteria</th>
                        <th>Bloccato</th>
                        <th>Commento</th>
                        <th>Valore</th>
                        <th>Stato</th>
                        <th>Modifica</th>
                        <th>Elimina</th>
                    </tr>
                </thead>

                <tbody>
                    {% for valutazione in valutazioni_attive %}
                    <tr>
                        <td>{{ valutazione.pk }}</td>
                        <td><a href="{% url 'users:userdetail' valutazione.utente.id %}" class="btn-primary">{{ valutazione.utente.username }}</a></td>
                        <td>{{ valutazione.prodotto.modello.nome }}</td>
                        <td>{{ valutazione.prodotto.nome }}</td>
                        <td>{{ valutazione.memoria }} GB</td>
                        <td>{{ valutazione.condizione }}

                        {% if valutazione.schermo_rotto %}
                            <td>✔</td>
                        {% else %}
                            <td>❌</td>
                        {% endif %}

                        {% if valutazione.back_rotto %}
                            <td>✔</td>
                        {% else %}
                            <td>❌</td>
                        {% endif %}
                        
                        <td>{{ valutazione.stato_batteria }} %</td>

                        {% if valutazione.bloccato %}
                            <td>✔</td>
                        {% else %}
                            <td>❌</td>
                        {% endif %}
                        
                        {% if valutazione.commento %}
                            <td><a class="btn-primary" type="button"
                                data-bs-toggle="popover" data-bs-placement="right"
                                data-bs-custom-class="custom-popover"
                                data-bs-title="Commento"
                                data-bs-content="{{valutazione.commento}}">
                                Leggi
                            </a></td>
                        {% else %}
                        <td>No</td>
                        {% endif %}

                        <td>{{ valutazione.valore }} €</td>

                        {% if valutazione.completata %}
                            <td>✔</td>
                        {% else %}
                            <td>⏳</td>
                        {% endif %}
                        
                        <!-- Modifica -->
                        <td>
                            <a href="{% url 'users:selected_valutazione_update' valutazione.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                    <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708z"></path>
                                </svg>
                            </a>
                        </td>
                        
                        <!-- Elimina -->
                        <td>
                            <a href="{% url 'users:selected_valutazione_delete' valutazione.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                </svg>
                            </a>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
                
            </table>

        {% else %}
            <p>Non hai nessuna valutazione.</p>
        {% endif %}

    {% endif %}
    
</div>

rplab/users/templates/users/user_detail.html
{% extends 'users/dashboard_base.html' %}

{% block dashboard %}

    <div class="container mt-5">
        <div class="card">
            <div class="card-header">
                <h2>Dettagli dell'utente: {{ utente.username }}</h2>
            </div>
            
            <!-- Dettagli utente -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <p><strong>Username:</strong> {{ utente.username }}</p>
                    </div>
                    <div class="col-md-6">
                        <p><strong>Email:</strong> {{ utente.email }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <p><strong>Nome:</strong> {{ utente.first_name }}</p>
                    </div>
                    <div class="col-md-6">
                        <p><strong>Cognome:</strong> {{ utente.last_name }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <p><strong>Data di registrazione:</strong> {{ utente.date_joined }}</p>
                    </div>
                    <div class="col-md-6">
                        <p><strong>Ultimo accesso:</strong> {{ utente.last_login }}</p>
                    </div>
                </div>

                <!-- Operazioni -->
                <div class="mt-4">
                    <a href="{% url 'users:userupdate' utente.id%}" class="btn btn-primary">Modifica profilo</a>
                    <a href="{% url 'users:userlist' %}" class="btn btn-secondary">Torna alla lista utenti</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

rplab/users/templates/users/user_list.html
{% extends 'users/dashboard_base.html' %}

{% block dashboard %}

    <!-- Lista di tutti gli utenti -->
    <div class="container mt-5 text-center">
        <h2 class="mb-4">Lista degli Utenti</h2>

        <!-- Tabella -->
        <table class="table table-bcomandaed">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Dettagli</th>
                </tr>
            </thead>
            
            <tbody>
                {% for utente in utente %}
                <tr>
                    <td>{{ utente.id }}</td>
                    <td>{{ utente.username }}</td>
                    <td>{{ utente.email }}</td>
                    <td>
                        <a href="{% url 'users:userdetail' utente.id %}" class="btn btn-info">Vedi Dettagli</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="text-center">
        <a href="{% url 'users:dashboard' %}" class="btn btn-secondary">Indietro</a>
    </div>
    
{% endblock %}