rplab/rplab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from .initcmds import *

urlpatterns = [
    path('admin/', admin.site.urls), #AdminPage
    path('', home, name='home'), #HomePage
    path('home/', home, name='home'), #HomePage
    path('servizi/', servizi, name="servizi"), #Servizi
    path('about/', about, name="about"), #About
    path('contatti/', contatti, name="contatti"), #Contatti

    path('shop/', include('shop.urls')), #Shop App
    path('users/', include('users.urls')),  # Users App
    path('sell/', include('sell.urls')),  # Sell App

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#erase_db()
init_database()

rplab/sell/urls.py
from django.urls import path
from . import views

app_name = 'sell'

urlpatterns = [
    path('', views.home, name="homesell"), #Home
    path('valutazione/', views.valutazione, name="valutazione"), # Form valutazione 
    path('valutazione/success/<str:valutazione>', views.success, name="success"), # Valutazione eseguita
]

rplab/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.register, name='register'), # Registazione utente
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'), # Login utente
    path('logout/', views.custom_logout, name='logout'), # Logout
    path('dashboard/', views.dashboard, name='dashboard'), # Dashboard
    path('comande/', views.all_comande_staff, name='allcomande'), # Tutte le comande (staff_only)
    path('valutazioni/', views.all_valutazioni_staff, name='allvalutazioni'), # Tutte le valutazioni (staff_only)
    path('', views.UserListView.as_view(), name='userlist'),  #Tutti gli utenti (staff_only)
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='userdetail'), # Dettagli utente
    path('users/<int:pk>/edit/', views.UserUpdateView.as_view(), name='userupdate'), # Modifica utente

    # CRUD HomePage
    path('gestione', views.crud_operations, name="gestione"),

    # Create
    path('createbrand', views.BrandCreateView.as_view(), name="brand_create"),
    path('createprodotto', views.ProdottoCreateView.as_view(), name="prodotto_create"),
    path('createdettaglio', views.DettaglioCreateView.as_view(), name="dettaglio_create"),
    path('createcomanda', views.ComandaCreateView.as_view(), name="comanda_create"),
    path('createvalutazione', views.ValutazioneCreateView.as_view(), name="valutazione_create"),

    # Select model to update
    path('select-brand-to-update', views.select_brand_to_update, name="brand_update"),
    path('select-prodotto-to-update', views.select_prodotto_to_update, name="prodotto_update"),
    path('select-dettaglio-to-update', views.select_dettaglio_to_update, name="dettaglio_update"),
    path('select-comanda-to-update', views.select_comanda_to_update, name="comanda_update"),
    path('select-valutazione-to-update', views.select_valutazione_to_update, name="valutazione_update"),

    # Update
    path('updatebrand/<int:pk>', views.BrandUpdateView.as_view(), name="selected_brand_update"), 
    path('updateprodotto/<int:pk>', views.ProdottoUpdateView.as_view(), name="selected_prodotto_update"),
    path('updatedettaglio/<int:pk>', views.DettaglioUpdateView.as_view(), name="selected_dettaglio_update"),
    path('updatecomanda/<int:pk>', views.ComandaUpdateView.as_view(), name="selected_comanda_update"),
    path('updatevalutazione/<int:pk>', views.ValutazioneUpdateView.as_view(), name="selected_valutazione_update"),

    # Select model to delete
    path('delete-brand-to-update', views.select_brand_to_delete, name="brand_delete"),
    path('delete-prodotto-to-update', views.select_prodotto_to_delete, name="prodotto_delete"),
    path('delete-dettaglio-to-update', views.select_dettaglio_to_delete, name="dettaglio_delete"),
    path('delete-comanda-to-update', views.select_comanda_to_delete, name="comanda_delete"),
    path('delete-valutazione-to-update', views.select_valutazione_to_delete, name="valutazione_delete"),


    # Delete
    path('deletebrand/<int:pk>', views.BrandDeleteView.as_view(), name="selected_brand_delete"), 
    path('deleteprodotto/<int:pk>', views.ProdottoDeleteView.as_view(), name="selected_prodotto_delete"),
    path('deletedettaglio/<int:pk>', views.DettaglioDeleteView.as_view(), name="selected_dettaglio_delete"),
    path('deletecomanda/<int:pk>', views.ComandaDeleteView.as_view(), name="selected_comanda_delete"),
    path('deletevalutazione/<int:pk>', views.ValutazioneDeleteView.as_view(), name="selected_valutazione_delete"),
]

rplab/sell/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from shop.models import Prodotto
from django.contrib.auth.models import User
from shop.models import Memorie

#Possibili condizioni della valutazione

class Condizioni(models.TextChoices):
    EXCELLENT = "excellent", "Eccellente"
    GOOD = "good", "Buono"
    FAIR = "fair", "Discreto"
    DAMAGED = "damaged", "Danneggiato"
    NOT_WORKING = "not_working", "Non funzionante"


# Modello per la valutazione di un dispositivo

class Valutazione(models.Model):
    utente = models.ForeignKey(User, on_delete=models.CASCADE) # Utente
    prodotto = models.ForeignKey(Prodotto, on_delete=models.CASCADE) # Prodotto da valutare
    memoria = models.PositiveIntegerField(choices=Memorie.choices) # Memoria del dispositivo
    condizione = models.CharField(max_length=20, choices=Condizioni.choices) # Condizione del dispositivo
    schermo_rotto = models.BooleanField(default=False) # Ha lo schermo rotto?
    back_rotto = models.BooleanField(default=False) # Ha il vetro posteriore rotto?
    stato_batteria = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)]) # Percentuale stato batteria?
    bloccato = models.BooleanField(default=False, help_text="Il telefono è bloccato dalla casa produttrice?") # Bloccato da casa produttrice?
    commento = models.CharField(blank=True, null=True, max_length=200, help_text="Aggiungi ulteriori commenti sullo stato del dispositivo") # Ulteriori commenti
    valore = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, help_text="Valore stimato del dispositivo") # Valore calolcato
    completata = models.BooleanField(blank=False, null=False, default=False) # Valutazione completata da dipendente

    def __str__(self):
        return f"Valutazione di {self.prodotto} - Utente: *{self.utente.username}*"

    class Meta:
        verbose_name_plural = "Valutazioni"

rplab/sell/forms.py
from django import forms
from .models import Valutazione
from shop.models import *

# Possibili condizioni della valutazione

CONDITION_CHOICES = [
        ("excellent", "Eccellente"),
        ("good", "Buono"),
        ("fair", "Discreto"),
        ("damaged", "Danneggiato"),
        ("not_working", "Non funzionante"),
    ]

# Possibili memorie della valutazione

MEMORY_CHOICES = [
    (64, '64 GB'),
    (128, '128 GB'),
    (256, '256 GB'),
    (512, '512 GB'),
    (1024, '1 TB'),
    ]


# Form per la valutazione

class ValutazioneForm(forms.ModelForm):

    memoria = forms.ChoiceField(choices=MEMORY_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    condizione = forms.ChoiceField(choices=CONDITION_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Valutazione
        fields = ['prodotto', 'memoria', 'condizione', 'schermo_rotto', 'back_rotto', 'stato_batteria', 'bloccato', 'commento']
        widgets = {
            'prodotto': forms.Select(attrs={'class': 'form-control'}),
            'schermo_rotto': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'back_rotto': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'stato_batteria': forms.NumberInput(attrs={'class': 'form-control'}),
            'bloccato': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'commento': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

    # Imposta i prodotti in ordine alfabetico
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['prodotto'].queryset = Prodotto.objects.all().order_by('nome')

rplab/sell/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from decimal import Decimal
from .forms import *
from .models import *


# Vista per la HomeSell

def home(request):
    return render(request, "sell/home_sell.html")


# Vista per il form di valutazione

@login_required
def valutazione(request):
    if request.method == 'POST':
        form = ValutazioneForm(request.POST)
        if form.is_valid():
            valutazione = form.save(commit=False)
            valutazione.utente = request.user


            # Valutazione prezzo
            prezzo = get_object_or_404(Dettagli, prodotto=valutazione.prodotto, condizione="new", memoria=valutazione.memoria).prezzo * Decimal(0.9)

            if(valutazione.condizione == 'excellent'): #Se condizione == eccellente, prezzo uguale
                pass
            elif(valutazione.condizione == 'good'): #Se condizione == buono, prezzo -10%
                prezzo *= Decimal(0.9)
            elif(valutazione.condizione == 'fair'): #Se condizione == discreto, prezzo -20%
                prezzo *= Decimal(0.8)
            elif(valutazione.condizione == 'damaged'): #Se condizione == danneggiato, -35%
                prezzo *= Decimal(0.65)
            elif(valutazione.condizione == 'not_working'): #Se condizione == non funzionante, -65 %
                prezzo *= Decimal(0.45)
            
            if(valutazione.schermo_rotto): #Se schermo è rotto, prezzo -50%
                prezzo *= Decimal(0.5)
            
            if(valutazione.back_rotto): #Se back è rotto, prezzo - 30%
                prezzo *= Decimal(0.7)

            if(valutazione.stato_batteria >= 95 and valutazione.stato_batteria <= 100): #Se stato batteria compreso tra 95 e 100, prezzo uguale
                pass
            elif(valutazione.stato_batteria >= 90 and valutazione.stato_batteria < 95): #Se stato batteria compreso tra 90 e 94, prezzo -10%
                prezzo *= Decimal(0.9)
            elif(valutazione.stato_batteria >= 80 and valutazione.stato_batteria < 90): #Se stato batteria compreso tra 80 e 89, prezzo -15%
                prezzo *= Decimal(0.85)
            else: #Se stato batteria compreso minore di 79, prezzo -25%
                prezzo *= Decimal(0.75)

            if(valutazione.bloccato):
                prezzo *= Decimal(0.25) #Se bloccato da casa produttrice, prezzo -75%

            valutazione.valore = prezzo

            valutazione.save()
            return redirect('sell:success', valutazione.valore)  # Reindirizza dopo il salvataggio
    else:
        form = ValutazioneForm()

    context = {
        'prodotti': Prodotto.objects.all(),
        'form':form,
    }
    return render(request, 'sell/valutazione.html', context)


# Vista per la pagina di successo

def success(request, valutazione):
    valutazione = round(Decimal(valutazione), 2)
    return render(request, 'sell/success.html', {"prezzo":valutazione})

rplab/sell/templates/sell/base_sell.html
{% extends 'base.html' %}

{% block head %}
    {% load static %}
{% endblock %}

{% block content %}

    {% block nav %}

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'sell:homesell' %}">Vendi il tuo usato</a>

                <!-- Link a destra -->
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:dashboard' %}">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <form method="post" action="{% url 'users:logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-link nav-link" style="color: black; border: none; background: none;">Logout</button>
                            </form>
                        </li>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Registrati</a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </nav>

    {% endblock %}

{% endblock %}

rplab/sell/templates/sell/home_sell.html
{% extends "sell/base_sell.html" %}

{% block head %}
    {% load static %}
{% endblock %}


{% block content %}

    <!-- Hero Section -->
    <section class="hero bg-primary text-white text-center py-5">
        <div class="container">
            <h1 class="display-4">Vendi il tuo telefono in pochi semplici passi</h1>
            <p class="lead">Scopri quanto vale il tuo telefono e ricevi una valutazione automatica direttamente online.</p>
        </div>
    </section>

    <!-- Come funziona -->
    <section id="how-it-works" class="py-5 bg-light">
        <div class="container">
            <h2 class="text-center mb-4">❓ Come funziona ❓</h2>
            <div class="row">
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title">1. Seleziona il tuo modello</h5>
                            <p class="card-text">Scegli il modello del tuo telefono per iniziare il processo di valutazione.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title">2. Rispondi alle domande</h5>
                            <p class="card-text">Rispondi a poche semplici domande sullo stato del tuo telefono.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title">3. Ottieni la valutazione</h5>
                            <p class="card-text">Ricevi una valutazione immediata e scopri quanto vale il tuo telefono.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Inizia Valutazione -->
    <section class="py-5">
        <div class="container text-center">
            <h2 class="mb-4">Inizia la valutazione del tuo telefono</h2>
            <p class="lead">Compila il modulo per ottenere una valutazione gratuita e senza impegno.</p>

            {% if user.is_authenticated%}
                <a href="{% url 'sell:valutazione' %}" class="btn btn-success btn-lg">Inizia Ora</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="btn btn-primary btn-lg">Accedi</a>
                <a href="{% url 'users:register' %}" class="btn btn-primary btn-lg">Registrati</a>
            {% endif %}
            
            </div>
    </section>

{% endblock %}

rplab/sell/templates/sell/success.html
{% extends 'sell/base_sell.html' %}

{% block content %}

  <!-- Pagina di acquisto confermato -->
  <div class="container text-center mt-5">
    <div class="alert alert-success" role="alert">
        <h1 class="display-4">Il tuo dispositivo vale <span style="color: green;">{{prezzo}}</span> €</h1>
        <p class="lead">La valutazione del tuo telefono è stata completata con successo!</p>
        <hr>
        <p>Puoi vedere tutte le tue valutazioni nella sezione <a href="{% url 'users:dashboard' %}">dashboard</a></p>
    </div>
    <a href="{% url 'sell:homesell' %}" class="btn btn-primary btn-lg mt-3">Vendi ancora</a>
</div>
  
{% endblock %}

rplab/sell/templates/sell/valutazione.html
{% extends 'sell/home_sell.html' %}

{% block content %}

    <!-- Form per la selezione del modello da operare -->
    <div class="container mt-5">
        <h1 class="text-center">Valutazione del Dispositivo</h1>
        <p class="text-center">Seleziona un prodotto e compila il modulo per la valutazione.</p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success w-100">Invia Valutazione</button>
        </form>
    </div>

{% endblock %}